#spring.application.name=OsooProduction
#spring.datasource.url=jdbc:mysql://localhost:3306/vasilis
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.show-sql=true
## Format the SQL for readability
#spring.jpa.properties.hibernate.format_sql=true
#
## Show parameter values in logs
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.application.name=OsooProduction
spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Default logging (can override in profile-specific)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# File upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
app.cors.allowed-origins=http://localhost:4200
jwt.secret=MXlPagAXjSDRgvdnwYWPv/+iCUOPJaPBMu5XcRxVmw0=
