spring.datasource.url=jdbc:mysql://localhost:3306/billmek
spring.datasource.username=root
spring.datasource.password=root

# (optional) dev-specific logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE