spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO

# later, set this to the real Angular domain (example)
app.cors.allowed-origins=http://app.photofaliro.gr,https://app.photofaliro.gr
